SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS Booking;
DROP TABLE IF EXISTS Client;
DROP TABLE IF EXISTS Shops;
DROP TABLE IF EXISTS bike_complement;
DROP TABLE IF EXISTS Complement;
DROP TABLE IF EXISTS Bikes;

SET FOREIGN_KEY_CHECKS = 1;